# Generated by Django 4.1.2 on 2022-10-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='shop_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.shop_details'),
        ),
    ]
