# Generated by Django 4.1.2 on 2022-10-20 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0002_alter_users_shop_id_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand_details',
            name='product_type_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.product_type'),
        ),
        migrations.AlterField(
            model_name='sale_transactions',
            name='brand_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.brand_details'),
        ),
        migrations.AlterField(
            model_name='sale_transactions',
            name='product_type_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.product_type'),
        ),
        migrations.AlterField(
            model_name='sale_transactions',
            name='shop_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.shop_details'),
        ),
        migrations.AlterField(
            model_name='stock_details',
            name='product_type_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.product_type'),
        ),
        migrations.AlterField(
            model_name='stock_details',
            name='shop_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.shop_details'),
        ),
        migrations.AlterField(
            model_name='stock_recived_details',
            name='brand_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.brand_details'),
        ),
        migrations.AlterField(
            model_name='stock_recived_details',
            name='product_type_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.product_type'),
        ),
        migrations.AlterField(
            model_name='stock_recived_details',
            name='shop_id_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_app.shop_details'),
        ),
    ]
